export interface buttonState {
    type?: 'submit' | 'reset' | 'button',
    title: string,
    color?: string,
    padding?: string,
    fontWeight?: string,
    cursor?: string,
    maxLength?: number,
    background?: string,
    border?: string,
    borderRadius?: string,
    onClick?: React.MouseEventHandler<HTMLButtonElement>,
    margin?: string,
    borderBottom?: any,
    fontSize?: string,
    width?: string,
}