import beerImg from "../../assests/img/product.png";
import cocaColaImg from "../../assests/img/Coca-cola.jpg";
import fish from "../../assests/img/fish.png";
import meat from "../../assests/img/meat.png";
import chease from "../../assests/img/chease.jpg";
import snack from "../../assests/img/snack.jpg";
import other from "../../assests/img/other.jpg";

export const BeerExample = [
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    stock: "-10%",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    stock: "1+1=3",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: beerImg,
    productTitle: "Пиво Jaws «Атомная Прачечная»",
    productGrade: "Светлое, 0.5 л",
    productSubtitle: "Алкоголь: 4,0% Плотность: 16,0%",
    productProduction: "Производство: Бельгия",
    productPrice: "105 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
];

export const beveragesExaple = [
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
  {
    productImg: cocaColaImg,
    productTitle: "Кока-кола»",
    productGrade: "0.5 л",
    productSubtitle: "Алкоголь: 0%",
    productProduction: "Производство: Россия",
    productPrice: "50 ₽",
    productCount: "цена за 1 шт",
    productTextButton: "В корзину",
  },
];

export const fishExaple = [
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: fish,
    productTitle: "Лещь",
    productGrade: "На развес",
    productSubtitle: "Вяленая",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
];

export const meatExaple = [
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: meat,
    productTitle: "Вяленое мясо",
    productGrade: "На развес",
    productSubtitle: "Вяленое",
    productProduction: "Производство: Россия",
    productPrice: "450 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
];

export const cheaseExaple = [
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: chease,
    productTitle: "Пармезан",
    productGrade: "На развес",
    productSubtitle: "Мягкий сыр",
    productProduction: "Производство: Италия",
    productPrice: "250 ₽",
    productCount: "цена за 100 гр",
    productTextButton: "В корзину",
  },
];

export const snackExaple = [
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
  {
    productImg: snack,
    productTitle: "Чипсы Rice Up",
    productGrade: "1 шт",
    productSubtitle: "Чипсы",
    productProduction: "Производство: Россия",
    productPrice: "150 ₽",
    productCount: "цена за 60 гр",
    productTextButton: "В корзину",
  },
];

export const otherExaple = [
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
  {
    productImg: other,
    productTitle: "Ягуар Оригинальный",
    productGrade: "1 шт",
    productSubtitle: "Алкоголь: 7,0% Плотность: 16,0%",
    productProduction: "Производство: Россия",
    productPrice: "Бесценно",
    productCount: "цена за 0.5 мл",
    productTextButton: "В корзину",
  },
];
